[package]
name = "float-window"
version = "0.1.0"
edition = "2024"

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
env_logger.workspace = true
image.workspace = true
log.workspace = true
muda.workspace = true
noise.workspace = true
pollster.workspace = true
rand.workspace = true
resvg.workspace = true
rfd.workspace = true
tiny-skia.workspace = true
tray-icon.workspace = true
wgpu.workspace = true
winit.workspace = true
