[package]
name = "screenshot-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
winit.workspace = true
softbuffer.workspace = true
xcap.workspace = true
arboard.workspace = true
image.workspace = true
anyhow.workspace = true
raw-window-handle.workspace = true
glam.workspace = true
objc.workspace = true
wgpu.workspace = true
pollster.workspace = true
rfd.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
